### ISSUE TITLE
🏆 Awesome and epic initiative from GvilG

### ISSUE THREAD

**Issue by GVilG** [unaizorrilla-githubschool/AccionaNonDevelopers#34]
- [ ] 🎸 A feature from GvilG that rocks
- [ ] ⚡ Another epic feature from GvilG
- [ ]  🔥 Hot feature from GvilG
