### ISSUE TITLE
🏆  Awesome and epic initiative from wisiwii

### ISSUE THREAD

**Issue by wisiwii** [unaizorrilla-githubschool/AccionaNonDevelopers#38]
- [ ] 🎸 A feature from wisiwii that rocks
- [ ] 🐧 Another epic feature from wisiwii
- [ ] 🔥 Hot feature from wisiwii
