### ISSUE TITLE
🏆 Awesome and epic initiative from iTzalin78

### ISSUE THREAD

**Issue by itzalin78** [unaizorrilla-githubschool/AccionaNonDevelopers#40]
# New Epic Iniative

- [ ] 🎸 A feature from iTzalin78 that rocks
- [ ] ⚡ Another epic feature from iTzalin78 
- [ ] 🔥 Hot feature from iTzalin78
