### ISSUE TITLE
🏆 Awesome and epic initiative from @Jomoqui1

### ISSUE THREAD

**Issue by Jomoqui1** [unaizorrilla-githubschool/AccionaNonDevelopers#55]
- [ ]  🎸 A feature from @Jomoqui1 that rocks
- [ ]  ⚡ Another epic feature from @Jomoqui1
- [ ]  🔥 Hot feature from @Jomoqui1
