### ISSUE TITLE
🏆 Awesome and epic initiative from @Franmi

### ISSUE THREAD

**Issue by Franmi** [unaizorrilla-githubschool/AccionaNonDevelopers#68]
- [ ] 🎸 A feature from [username] that rocks

- [ ]  ⚡ Another epic feature from [username]

- [ ] 🔥 Hot feature from [username]
