### ISSUE TITLE
🏆 Awesome and epic initiative from c-gomez-m

### ISSUE THREAD

**Issue by c-gomez-m** [unaizorrilla-githubschool/AccionaNonDevelopers#74]
# **Description of the epic** 

 

- [ ] 🎸 A feature from [c-gomez-m] that rocks
- [ ] ⚡ Another epic feature from [c-gomez-m]
- [ ] 🔥 Hot feature from [c-gomez-m]
